# Generated by Django 4.1.3 on 2022-11-26 04:36

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_remove_student_birthday'),
    ]

    operations = [

        migrations.CreateModel(
            name='Quizs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idText', models.FloatField()),
                ('phrase', models.CharField(max_length=150)),
                ('reponse1', models.CharField(max_length=150)),
                ('reponse2', models.CharField(max_length=150)),
                ('reponse3', models.CharField(max_length=150)),
                ('reponse4', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('old_password', models.CharField(max_length=30)),
                ('new_password', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
       
        migrations.CreateModel(
            name='TextTts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('audio_file', models.FileField(blank=True, upload_to='audio/')),
            ],
        ),
       
    ]
