# Generated by Django 4.1.3 on 2022-12-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_quizs_settingsaccount_texts_texttts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texttts',
            old_name='text',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='quizs',
            name='idText',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='texttts',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
